apiVersion: v1
kind: Pod
metadata:
  name: kafka-jmx-monitor
  labels:  
    app: kafka-jmx-monitor 
  annotations:
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "8080"
    "prometheus.io/path": "/metrics"
spec:
  containers:
  - name: kafka-jmx-monitor
    image: chriswatkinsibm/kafka-jmx-monitor:latest
    securityContext:
      allowPrivilegeEscalation: false      
      capabilities:
        drop:
          - all    
    envFrom:
    - configMapRef:
        name: kafka-jmx-monitor-config    
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: kafka-jmx-monitor-config    
      mountPath: /opt/kafka-jmx-monitor/metrics.txt
      subPath: metrics.txt
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000    
    seccompProfile:
      type: RuntimeDefault    
  volumes:
  - name: kafka-jmx-monitor-config    
    configMap:
      name: kafka-jmx-monitor-config    
